# Site settings
title: Barks n Bytes
subtitle: >-
  My corner of the internet for thoughts, research notes, and reflections on technology and science.
email: m.martorana@ik.me

description: >-
  Margherita Martorana writes about AI, robotics, neurosymbolic systems, knowledge graphs, ontologies, LLMs, and multimodal models.

baseurl: "/barks.n.bytes"
url: "https://ritamargherita.github.io"
github_username: ritamargherita

# Optional but useful for SEO plugins / themes
tagline: >-
  AI • Robotics • Neurosymbolic Systems • Knowledge Graphs • LLMs

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"